language: node_js
sudo: true
dist: trusty

node_js:
  - '6'

branches:
    only:
        - master

env:
    global:
        - CHROME_BIN=/usr/bin/google-chrome
        - DISPLAY=:99.0

cache:
  directories:
     - node_modules

before_install:
     - export CHROME_BIN=/usr/bin/google-chrome
     - export DISPLAY=:99.0
     - sh -e /etc/init.d/xvfb start
     - sudo apt-get update
     - sudo apt-get install -y libappindicator1 fonts-liberation
     - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
     - sudo dpkg -i google-chrome*.deb
     - ./scripts/setup-github-access.sh

after_success:
    # deploy github page
    - ./scripts/delete-gh-pages.sh
    - git status; npm run deploy-gh-pages
    - git checkout master
    # give github a little bit of time to update the github page
    - sleep 10
    # run e2e test on the github page
    - tsc -p e2e
    - npm run e2e config/protactor.sauce.conf.js

notifications:
    email: false